"""Fix user_id fiels in MS

Revision ID: 08d0a81d93ff
Revises: 000002
Create Date: 2023-11-30 20:32:23.050610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000003'
down_revision: Union[str, None] = '000002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meteo_station', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('meteo_station_id_user_fkey', 'meteo_station', type_='foreignkey')
    op.create_foreign_key(None, 'meteo_station', 'user', ['user_id'], ['id'])
    op.drop_column('meteo_station', 'id_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meteo_station', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meteo_station', type_='foreignkey')
    op.create_foreign_key('meteo_station_id_user_fkey', 'meteo_station', 'user', ['id_user'], ['id'])
    op.drop_column('meteo_station', 'user_id')
    # ### end Alembic commands ###
