"""Creating meteostation table

Revision ID: c269e8f5f58b
Revises: 000001
Create Date: 2023-11-30 19:04:08.244140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000002'
down_revision: Union[str, None] = '000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meteo_station',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('has_video_server', sa.Boolean(), nullable=False),
    sa.Column('video_server_ip', sa.String(), nullable=False),
    sa.Column('video_server_port', sa.String(), nullable=False),
    sa.Column('video_server_stream_path', sa.String(), nullable=False),
    sa.Column('has_timelapse', sa.Boolean(), nullable=False),
    sa.Column('video_server_snapshot_path', sa.String(), nullable=False),
    sa.Column('os_login', sa.String(), nullable=False),
    sa.Column('os_password_hash', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meteo_station')
    # ### end Alembic commands ###
