"""Create table user

Revision ID: 1abc9f607ebe
Revises: 
Create Date: 2023-11-19 00:58:07.653717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '000001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('surname', sa.String(), nullable=True),
                    sa.Column('login', sa.String(), nullable=False),
                    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('password_hash', sa.String(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
